<?php
require_once dirname(__FILE__) . '/includes/page.inc';

function islandora_list_collections_menu(){
  $items = array();
  $items['admin/collections_list'] = array(
    'title' => 'Collection List',
    'access callback' => TRUE,
    'page callback' => 'create_page variables_to_page',
    'type' => 'NORMAL_MENU_ITEM',
  );
  return $items;
}

function variables_to_page(){
  $content = array();
  $content[] = array(
    '#type' => 'markup',
    '#markup' => theme('list_collections', array('list' => collection_list())),
  );
  return $content;
}

function islandora_list_collections_theme($existing, $type, $theme, $path){
  //a default structure for our $variables to be passed to template
  return array(
    'list_collections' => array(
      'variables' => array('list' => array()),
      'template' => 'theme/islandora-list-collections',
    ),
  );
}

function islandora_list_collection_islandora_object_ingested(AbstractObject $object) {
  if(in_array('islandora:collectionCModel', $object->models)) {
      //re-run the collection list
      collection_list();
  }
}
