<?php
require_once dirname(__FILE__) . '/includes/page.inc';


function islandora_list_collection_page(){
  echo 'hello world';
}


function islandora_list_collections_menu(){
  $items = array();
  $items['admin/collections_list'] = array(
    'title' => 'Collection List',
    'access callback' => TRUE,
    'page callback' => 'create_page',
    'type' => 'NORMAL_MENU_ITEM',
  );
  return $items;
}

