<?php
require_once dirname(__FILE__) . '/includes/page.inc';


function islandora_list_collection_page(){
  echo 'hello world';
}


function islandora_list_collections_menu(){
  $items = array();
  $items['admin/collections_list'] = array(
    'title' => 'Collection List',
    'access callback' => TRUE,
    'page callback' => 'create_page',
    'type' => 'NORMAL_MENU_ITEM',
  );
  return $items;
}


function islandora_list_collections_theme($existing, $type, $theme, $path){
  return array(
    'list_collections' => array(
      'variables' => array(),//collection_list(),
      'template' => 'theme/islandora-list-collections',
    ),
  );
}


function islandora_list_collection_islandora_object_ingested(AbstractObject $object) {
  if(in_array('islandora:collectionCModel', $object->models)) {
      //re-run the collection list
      collection_list();
  }
}
